export type APIEvent =
	'getPosts'
	| 'createPost'
	| 'deletePost'
	| 'updatePost'
	| 'getUsers'
	| 'getUser'
	| 'createUser'
	| 'updateUserPhoto'
	| 'getLikes'
	| 'createLike'
	| 'unlike'
	| 'getUserLikes'
	| 'getPostLikes'
	| 'postsUpdate'

